import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acelera Movies",
  description: "Generated by create next app",
  viewport:"initial-scale=1, width=device-width"
};
//<meta name="viewport" content="initial-scale=1, width=device-width" />
//ver se realmente éaqui que adicionamos essa tag
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
